dbt_transform:
  outputs:
    dev:
      dataset: shopping_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: 
      location: US
      method: service-account
      priority: interactive
      project: 
      threads: 1
      type: bigquery
  target: dev